/* Automatically generated by cbindgen */

#ifndef VISIBLEDESK_H
#define VISIBLEDESK_H

/* Warning: Generated file, do not edit. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

struct LibVisInstance;

struct MonitorVisibleInfo {
  int64_t monitor_id;
  int64_t current_visible;
  int64_t max_visible;
  int64_t total_area;
};

extern "C" {

LibVisInstance *libvisdesk_init();

void libvisdesk_destroy(LibVisInstance *handle);

int32_t libvisdesk_get_visible_area(const LibVisInstance *handle,
                                    MonitorVisibleInfo **out_monitors,
                                    uintptr_t *out_num_monitors,
                                    int64_t *out_total_visible,
                                    int64_t *out_total_area);

void libvisdesk_free_monitors(MonitorVisibleInfo *monitors, uintptr_t num_monitors);

int32_t libvisdesk_watch_visible_area(LibVisInstance *handle,
                                      void (*callback)(const MonitorVisibleInfo*,
                                                       uintptr_t,
                                                       int64_t,
                                                       int64_t,
                                                       void*),
                                      uint64_t throttle_ms,
                                      void *user_data);

int32_t libvisdesk_stop_watch_visible_area(LibVisInstance *handle);

}  // extern "C"

#endif  // VISIBLEDESK_H
